### ISSUE TITLE
How could you calculate the correct radius multiplater

### ISSUE THREAD

**Issue by antonioreyna** [KogiMobileSAS/RoundedViews#1]
If i have a design on lets say Sketchapp in which corner is 4px rounded what would be the correct size for the multiplier?

What could be the way to calculate it from any design app.

thanks.

**Comment by juanuribeo13** [comment]
@antonioreyna This is the code that calculates the `cornerRadius`:

``` swift
let shortestDimmension = min(bounds.size.width, bounds.size.height)
layer.cornerRadius = shortestDimmension / radiusMultiplier
```

The idea behind using the `radiusMultiplier` is that the corners look the same so if you have a view of size 20x20 and another one of size 60x60 with the same `radiusMultiplier`, their corners will look the same. If you know what's the `cornerRadius` for a specific size then you can find the `radiusMultiplier` like this:

``` swift
let radiusMultiplier = shortestDimmension / cornerRadius
```

**Comment by antonioreyna** [comment]
Thanks!
